# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlOXPrVd0hEdDqhziyWQ8QZQ_qpRFGTg
"""

# Industry-Ready CLI Calculator by Harshitha
# Features: OOP Design, Error Handling, and Logging
# Improvements: Floating-point tolerance,imports, smoother input flow
# Sets up formal structured logging to track all operations, results, and errors

import math
import logging

# --- Logging Configuration ---
logging.basicConfig(
    filename="calculator.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

class Calculator:
    """A calculator supporting arithmetic operations."""

    def add(self, a, b): return a + b
    def subtract(self, a, b): return a - b
    def multiply(self, a, b): return a * b

    def divide(self, a, b):
        if b == 0:
            raise ZeroDivisionError("Division by zero!")
        return a / b

    def modulus(self, a, b):
        if b == 0:
            raise ZeroDivisionError("Modulus by zero!")
        return a % b

    def power(self, a, b): return a ** b

    def clean_result(self, result):
        """
        Return an integer if result is effectively whole (considering float fuzziness).
        Example: 1.0000000001 -> 1
        """
        if isinstance(result, (int, float)) and math.isclose(result, round(result), rel_tol=1e-9, abs_tol=1e-9):
            return int(round(result))
        return result


def get_number(prompt):
    """Keep prompting until a valid float is entered."""
    while True:
        val = input(prompt).strip()
        if val.lower() == "exit":
            return "exit"
        try:
            return float(val)
        except ValueError:
            print(Fore.RED + "❌ Please enter a valid numeric value.")


def main():
    calc = Calculator()
    print("\n🧮 Welcome to CLI Calculator!\n")
    print("Available Operations:")
    print("1️⃣  Addition (+)\n2️⃣  Subtraction (-)\n3️⃣  Multiplication (*)\n4️⃣  Division (/)\n5️⃣  Modulus (%)\n6️⃣  Power (**)\n")
    print("Type 'exit' anytime to quit.\n")

    while True:
        choice = input("Enter operation symbol (+, -, *, /, %, **) or 'exit': ").strip()
        if choice.lower() == 'exit':
            print("✅ Thank you for using the calculator. Goodbye! 👋")
            break

        if choice not in ['+', '-', '*', '/', '%', '**']:
            print("❌ Invalid operation! Please choose from +, -, *, /, %, **.\n")
            continue

        # Get first number safely
        num1 = get_number("Enter first number: ")
        if num1 == "exit": breakex

        # Get second number safely
        num2 = get_number("Enter second number: ")
        if num2 == "exit": break

        try:
            # Perform calculation
            if choice == '+':
                result = calc.add(num1, num2)
            elif choice == '-':
                result = calc.subtract(num1, num2)
            elif choice == '*':
                result = calc.multiply(num1, num2)
            elif choice == '/':
                result = calc.divide(num1, num2)
            elif choice == '%':
                result = calc.modulus(num1, num2)
            elif choice == '**':
                result = calc.power(num1, num2)

            # Clean up output for neat display
            formatted = calc.clean_result(result)
            print(f"✅ Result: {formatted}\n")

            # Log successful calculation
            logging.info(f"Operation: {num1} {choice} {num2} = {formatted}")

        except ZeroDivisionError as e:
            print( + f"⚠️ {e}\n")
            logging.warning(f"Attempted {e}")
        except Exception as e:
            print(f"Unexpected error: {e}\n")
            logging.error(f"Unexpected error: {e}")


if __name__ == "__main__":
    main()

